### ISSUE TITLE
Cannot read property 'db' of undefined

### ISSUE THREAD

**Issue by csandeep** [danecando/hapi-sequelized#22]
node v0.12.0
hapijs v8.4.0

Im not sure if this is a issue with my setup or not. I have the same error while accessing `db` via the `server.plugins['hapi-sequelized']` too.

```
➜  test  npm test

> hapi-sequelized@2.1.1 test /Users/sandeep/Downloads/hapi-sequelized-master
> lab

Unhandled rejection TypeError: Cannot read property 'db' of undefined
    at /Users/sandeep/Downloads/hapi-sequelized-master/test/index.js:53:57
    at done (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/hapi/node_modules/items/lib/index.js:22:21)
    at /Users/sandeep/Downloads/hapi-sequelized-master/lib/index.js:49:20
    at tryCatcher (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/sequelize/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:646:14)
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
    at Async._drainQueue (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/sequelize/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/sequelize/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/sandeep/Downloads/hapi-sequelized-master/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by danecando** [comment]
Did you update the connection settings / options in the test file? If it fails to authenticate for the db the tests will fail

**Comment by csandeep** [comment]
Turns out that the [passport-local-sequelize](https://github.com/madhurjain/passport-local-sequelize) and [sqlizr](https://github.com/mikefrey/sqlizr) don't play well together.

Minor nitpick in the example -- the call to `server.plugins['hapi-sequelized'].db.sequelize.sync()` (and the subsequent `server.start()`) should be within the `server.register()` callback.

**Comment by danecando** [comment]
@csandeep you're right. I will update that. I use it a bit differently in my application so I just kinda through the example together real quick. Did you notice the specific problem between those 2 plugins so maybe we can get it resolved?

**Comment by zachguo** [comment]
I got same error when trying to run `example` app. Connection options had been changed to match my local environment.

```
$ npm list --depth=0
/Users/syg/Downloads/example
├── hapi@8.6.1
├── hapi-sequelized@2.1.1
├── mysql@2.7.0
└── sequelize@3.2.0
```

**Comment by zachguo** [comment]
I also tried running `npm test` and all tests passed. But I notice in `tests`, `server.plugins['hapi-sequelized'].db.sequelize.sync()` is in the register callback, while in `example` it's not. It seems that `sqlizr` is not working.

**Comment by danecando** [comment]
It sounds like you're trying to call the sync before the plugin is registered. I need to update the example but  you should do the sync in the register callback like in the tests

**Comment by danecando** [comment]
ed41d495605e6ad9afe65d233e2220fce826db88

Sorry about the confusion. I updated the example the the readme. 

Please let me know if you're still having any problems

**Comment by zachguo** [comment]
Just tested it. `example` is working now.
